# Generated by Django 4.2.3 on 2023-07-22 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('contact_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('machine_class', models.CharField(max_length=50)),
                ('machine_serial', models.CharField(max_length=50)),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.TextField(max_length=600)),
                ('task_asses', models.TextField(max_length=600)),
                ('task_resolve', models.TextField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('select_delivery', models.CharField(choices=[('Curier', 'Curier'), ('Predat Client ', 'predare'), ('Ridicat Dantex', 'dtx')], max_length=14)),
                ('select_status', models.CharField(choices=[('garantie', 'Garantie'), ('post_garantie', 'Post Garantie'), ('extern', 'Extern')], max_length=14)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
            ],
            options={
                'ordering': ['complete'],
            },
        ),
    ]
